name: hello
base: core
version: '0.1'
summary: work please
description: |
  I would like it very much if you would work.
grade: devel
confinement: devmode

apps:
  snap-goble-and-pop:
    command: bin/snap-goble-and-pop

parts:
  snap-goble-and-pop:
    source: .
    plugin: go
    #  go-ble:
    #    source: ../github.com/go-ble/ble
    #    plugin: go
    #    source-type: git
    #  paho-mqtt-golang:
    #    source: ../github.com/eclipse/paho.mqtt.golang
    #    plugin: go
    #    source-type: git

