name: snap-goble-and-pop # you probably want to 'snapcraft register <name>'
base: core # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Scans for local BLE devices and blasts them out over MQTT # 79 char long summary
description: |
  This is a test app for go-ble and poho.mqtt.golang
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


parts:
  snap-goble-and-pop:
    # See 'snapcraft plugins'
    plugin: go
    #go-importpath: github.com/gchaincl/httplab
    source: ., ../github.com
    source-type: git

