name: snap-goble-and-pop
version: "0.1"
summary: Work now.
description: |
  work work work work work

confinement: devmode
base: core

parts:
  snap-goble-and-pop:
    plugin: go
    go-importpath: github.com/armaanhammer/snap-goble-and-pop
    source: .
    source-type: git
    build-packages:
      - gcc

apps:
  snap-goble-and-pop:
    command: bin/snap-goble-and-pop
