name: snap-goble-and-pop
version: "0.2"
summary: Scans for BLE devices, sends data about devices as JSON over MQTT
description: |
  Current iteration is proof-of-concept. When activated, it scans for all BLE devices, packages info found about devices as JSON, then sends that JSON out as MQTT.

confinement: devmode
base: core

parts:
  snap-goble-and-pop:
    plugin: go
    go-importpath: github.com/armaanhammer/snap-goble-and-pop
    source: .
    source-type: git
    build-packages:
      - gcc

apps:
  snap-goble-and-pop:
    command: bin/snap-goble-and-pop
